add favourite api
tttturtle-russ/ByteDance-Tiny-Douyin pull request #1
Opened 2023-08-20 11:33 UTC by whale-withme

2023-08-22 16:28 UTC, tttturtle-russ requested changes
函数名要写明白，不能是简单的`TotalAdd`之类的，我怎么知道add是什么呢？

2023-08-22 16:28 UTC, tttturtle-russ commented on model/model.go
> +
这两个结构体是什么意思

2023-08-22 16:28 UTC, tttturtle-russ commented on main.go
> +	err := db.InitMysql()
这里应该是`db.InitDB()`

2023-08-23 17:03 UTC, tttturtle-russ commented
@whale-withme 速度改，另外帮助sdw把他的也提交上来

2023-08-24 01:44 UTC, whale-withme commented
+// 定义Like表，记录点赞的id和对应的videoid +type LikeList struct { +	UserId  int64 `json:"user_id"` +	VideoId int64 `json:"video_id"` +} + +// 常用到userid和videoid的结构体 +type FavouriteInfo struct { +	UserId  int64 `json:"user_id"` +	VideoId int64 `json:"video_id"` 第一个结构体是记录存在用户给视频点赞关系的结构体，第二个是为了给service里面参数userid, videoid新建的结构体。db.InitDB()和函数名修改已完成




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tttturtle-russ/ByteDance-Tiny-Douyin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 凌晨0:28
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [tttturtle-russ/ByteDance-Tiny-Douyin] add favourite api (PR #1)





 
@tttturtle-russ requested changes on this pull request.
 
函数名要写明白，不能是简单的TotalAdd之类的，我怎么知道add是什么呢？

 
In model/model.go:
 &gt; +	Title         string `json:"title"`          // 视频标题 +	//UserFavourites []int64 `json:"user_favourites"` //点赞的用户id +} + +// 定义Like表，记录点赞的id和对应的videoid +type LikeList struct { +	UserId  int64 `json:"user_id"` +	VideoId int64 `json:"video_id"` +} + +// 常用到userid和videoid的结构体 +type FavouriteInfo struct { +	UserId  int64 `json:"user_id"` +	VideoId int64 `json:"video_id"` +} +  
这两个结构体是什么意思
 
 
In main.go:
 &gt;  	"ByteDance-Tiny-Douyin/routers"  	"log"  )    func main() { +	err := db.InitMysql()  
这里应该是db.InitDB()
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

2023-08-24 01:46 UTC, whale-withme commented on main.go
> +	err := db.InitMysql()
已修改

2023-08-24 01:47 UTC, whale-withme commented on model/model.go
> +
第一个结构体是记录存在用户给视频点赞关系的结构体，第二个是为了给service里面参数userid, videoid新建的结构体。

2023-08-29 12:58 UTC, tttturtle-russ approved these changes

2023-08-29 12:58 UTC, merged